// Estados de uma nave
const NAVE_OCIOSA = 0;
const NAVE_ROTACIONANDO_PARA_DESTINO = 1;
const NAVE_APONTANDO_PARA_DESTINO = 2;
const NAVE_MOVENDO_PARA_DESTINO = 3;
const NAVE_CHEGOU_DESTINO = 4;

// Tipos de ordens
const ORDEM_MOVIMENTACAO = 0;